name: 'Test Helm3 pipeline'
on: [push]
jobs:

  test:
    runs-on: 'self-hosted'
    services:
      chartmuseum:
        image: chartmuseum/chartmuseum:v0.12.0
        ports:
        - 8080:8080
        env:
          DEBUG: 1
          STORAGE: local
          STORAGE_LOCAL_ROOTDIR: /charts
          BASIC_AUTH_USER: admin
          BASIC_AUTH_PASS: test
        volumes:
        - /tmp:/charts

    steps:
    - uses: 'actions/checkout@v2'

    - name: 'Build docker image'
      run: 'docker build -t helm .'

    - name: 'Test helm v3 version'
      run: 'docker run --rm -i --entrypoint=helm helm version -c'

    - name: 'Test helm v3 push'
      uses: ./
      with:
        ChartFolder: 'chart'
        ChartSourcePath: '.github/'
        ChartmuseumRepoName: 'test'
        ChartmuseumUrl: 'http://chartmuseum:8080'
        ChartmuseumUsername: 'admin'
        ChartmuseumPassword: 'test'
        ChartVersion: '0.0.1-test'
        ChartAppVersion: '1.0.0-test'
        ForceUpload: 'True'
